### ISSUE TITLE
Installation error "cannot import name 'formatargspec' from 'inspect'"

### ISSUE THREAD

**Issue by tinue** [RhetTbull/osxphotos#2068]
**Describe the bug**
During installation with "pip install osxphotos" (after creating a venv) the installation errors out with "cannot import name 'formatargspec' from 'inspect'".

**To Reproduce**
1. Start with a fresh virtual environment
2. `pip install osxphotos`

**Desktop (please complete the following information):**
 - MacOS 26.2
 - Python 3.14.2 from homebrew
 - osxphotos version: n/a (installation error)

**Comment by RhetTbull** [comment]
I have replicated this but not sure how to fix it. Will take a look when I have time.  As a work around it does install fine if you use [uv](https://docs.astral.sh/uv/getting-started/installation/). 

```bash
uv pip install osxphotos
```

**Comment by tinue** [comment]
Thank you, I installed uv, and could successfully install osxphotos. Seems uv is so much faster than pip, I'll switch to this tool for good ;-)

**Comment by RhetTbull** [comment]
@tinue glad you got it working. uv is so much better! I will try to figure out why pip won't work as many people still use it. This appears to be an issue with one of the dependencies (whenever) but I can't figure out why it's failing.

**Comment by RhetTbull** [comment]
I've gotten `pip install osxphotos` working with v0.75.5
