### ISSUE TITLE
converting HEIC to JPEG  with --convert-to-jpeg throws error

### ISSUE THREAD

**Issue by thomashelders** [RhetTbull/osxphotos#562]
Hi,

exporting iPhone Pictures from the Photo Library which are in HEIC format and converting them to JPEG is throwing an error.

I am executing the command:
osxphotos --db /Volumes/Seagate\ Portable\ Drive/FotoLib_play/Fotos\ Library.photoslibrary export /Volumes/WD\ Book/Photos_Export/ --from-date "2021-12-01" --to-date "2021-12-31"  --convert-to-jpeg --jpeg-quality 1.0 --directory "{folder_album}" --exiftool

Exporting 227 photos to /Volumes/WD Book/Photos_Export...
  [------------------------------------]    0%Error exporting photo (3pcnTUjnQQKGYgx8xoe3vQ: IMG_5240.HEIC) as IMG_5240.jpeg: 'NoneType' object has no attribute 'writeJPEGRepresentationOfImage_toURL_colorSpace_options_error_'
  [------------------------------------]    0%  00:04:30Error exporting photo (c1dai4s8SampGJ4EPraaAQ: IMG_5306.HEIC) as IMG_5306.jpeg: 'NoneType' object has no attribute 'writeJPEGRepresentationOfImage_toURL_colorSpace_options_error_'
  [------------------------------------]    1%  00:04:29Error exporting photo (6HfXiSfsTseMzqOFt33BGA: IMG_5312.HEIC) as IMG_5312.jpeg: 'NoneType' object has no attribute 'writeJPEGRepresentationOfImage_toURL_colorSpace_options_error_'
...

I executed the command:
osxphotos --db /Volumes/Seagate\ Portable\ Drive/FotoLib_play/Fotos\ Library.photoslibrary debug-dump --dump photos --uuid '3pcnTUjnQQKGYgx8xoe3vQ' > debug_converting_heic_to_jpeg.txt

to get more details for the first picture. Output is attached.

Any idea what is the problem ?

[debug_converting_heic_to_jpeg.txt](https://github.com/RhetTbull/osxphotos/files/7788900/debug_converting_heic_to_jpeg.txt)

**Comment by RhetTbull** [comment]
I believe you said earlier you were running on High Sierra (10.13).  I've never tested the converter code on 10.13 but all the system calls used should work.  I do know it won't work on Sierra (10.12) because Sierra does not have the ability to read HEIC images but I believe High Sierra does.  The converter code uses Apple system framework calls to do the conversion so I'm dependent on whatever formats Apple supports on a given version of macOS but HEIC should be available on 10.13+.  

Could you try the following and post the output here?

Run: `osxphotos repl` which launches an interactive debug session of osxphotos (when done, type `q` to quit)

Then, in the interactive session that opens, type the following:
```
from osxphotos.imageconverter import ImageConverter
converter = ImageConverter()
converter.context
```

Expected output should be something like:

```
<CIContext: 0x7fd58fdf1dd0 (metal-IG 1) MTLDevice=0x7fd592196000>
    priority: default
    workingSpace: <CGColorSpace 0x7fd592e76fc0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB Linear)
    workingFormat: RGBAh
    downsampleQuality: High
```

**Comment by thomashelders** [comment]
Yes, correct. I am using High Sierra (10.13.6).
Unfortunately this last command does not give the expected output:

osxphotos repl
python version: 3.9.8 (main, Nov 21 2021, 18:06:12) 
[Clang 10.0.0 (clang-1000.10.44.4)]
osxphotos version: 0.43.8
Using last opened Photos library: /Volumes/Seagate Portable Drive/FotoLib_play/Fotos Library.photoslibrary
Loading database
Processing database /Volumes/Seagate Portable Drive/FotoLib_play/Fotos Library.photoslibrary/database/photos.db
Processing database.
Database version: 3301.
Processing persons in photos.
Processing detected faces in photos.
Processing albums.
Processing keywords.
Processing photo details.
Processing additional photo details.
Processing location data.
Processing face details.
Done processing details from Photos library.
Done: took 17.27 seconds
Getting photos
Found 25901 photos in 3.88 seconds

The following classes have been imported from osxphotos:
- AlbumInfo, ExifTool, PhotoInfo, PhotosDB, PlaceInfo, QueryOptions

The following variables are defined:
- photosdb: PhotosDB() instance for /Volumes/Seagate Portable Drive/FotoLib_play/Fotos Library.photoslibrary
- photos: list of PhotoInfo objects for all photos in photosdb, including those in the trash (len=25901)
- selected: list of PhotoInfo objects for any photos selected in Photos (len=0)

The following functions may be helpful:
- get_photo(uuid): return a PhotoInfo object for photo with uuid; e.g. get_photo('B13F4485-94E0-41CD-AF71-913095D62E31')
- get_selected(); return list of PhotoInfo objects for photos selected in Photos
- show(photo): open a photo object in the default viewer; e.g. show(selected[0])
- show(path): open a file at path in the default viewer; e.g. show('/path/to/photo.jpg')
- spotlight(photo): open a photo and spotlight it in Photos
- inspect(object): print information about an object; e.g. inspect(PhotoInfo)
- explore(object): interactively explore an object with objexplore; e.g. explore(PhotoInfo)
- q, quit, quit(), exit, exit(): exit this interactive shell

>>> from osxphotos.imageconverter import ImageConverter
>>> converter = ImageConverter()
>>> converter.context
>>>

**Comment by RhetTbull** [comment]
Thanks -- that's the problem...now I just need to figure out why.  What mac computer model are you using?

**Comment by thomashelders** [comment]
>>> from osxphotos.imageconverter import ImageConverter
>>> converter = ImageConverter()
>>> type(converter)
<class 'osxphotos.imageconverter.ImageConverter'>

>>> dir(converter)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'context', 'instance', 'write_jpeg']

>>> type(converter.context)
<class 'NoneType'>

>>>


I am using a Mac mini (Mid 2011)

**Comment by thomashelders** [comment]
When I select one of this .HEIC pictures in the Photo app, it is possible to export it as JPEG.
Isn't that using the same converter ?

**Comment by RhetTbull** [comment]
> When I select one of this .HEIC pictures in the Photo app, it is possible to export it as JPEG.
Isn't that using the same converter ?

Yes, it should be using the same converter as I'm using Apple's system libraries to do the conversion.  

Both those mac's have a GPU so not sure why this isn't working -- I'll keep exploring.  The converter code requires a GPU.

**Comment by RhetTbull** [comment]
I'm still trying to figure this out.  The image converter code works on my 2013 iMac running 10.12 (Sierra) so it should work on 10.13.  (Though 10.12 can't read HEIC).  The system calls I'm using should work on 10.11+.

**Comment by RhetTbull** [comment]
I think I figured this out and implemented a fix in [v0.44.3](https://pypi.org/project/osxphotos/0.44.3/).  The code was using Apple's "Metal" framework for GPU accelerated conversion but this only works on Macs from 2012 and newer.  I've switched the code to a system call that will fall back to CPU conversion if a supported GPU isn't available.  Unfortunately I can't test it as my Mac has a supported GPU.  Give the new version a try and let me know if it works.

**Comment by thomashelders** [comment]
with this new version, the conversion is working correct :-) Thanks a lot !!

for your information: I get the following converter.context, with the command used above:

osxphotos repl
python version: 3.9.8 (main, Nov 21 2021, 18:06:12) 
[Clang 10.0.0 (clang-1000.10.44.4)]
osxphotos version: 0.44.3
...
>>> from osxphotos.imageconverter import ImageConverter
>>> converter = ImageConverter()
>>> converter.context
<CIContext: 0x7fc29b163710 (opengl 1)>
    priority: high
    workingSpace: <CGColorSpace 0x7fc29afeaff0> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; sRGB Linear)
    workingFormat: RGBAh
    downsampleQuality: High

**Comment by RhetTbull** [comment]
Great! Happy New Year!
