### ISSUE TITLE
Installation fails with pipx on macOS

### ISSUE THREAD

**Issue by Qhilm** [RhetTbull/osxphotos#1672]
**Describe the bug**

Initial installation fails, pip fails to download osxmetadata 1.3.5 somehow:

>```
>Downloading osxmetadata-1.3.5-py3-none-any.whl.metadata (62 kB)
>PIP STDERR
>----------
>ERROR: Exception:
>Traceback (most recent call last):
>  File "/Users/cysimons/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
>    yield
>  File "/Users/cysimons/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
>    data = self._fp_read(amt) if not fp_closed else b""
>           ^^^^^^^^^^^^^^^^^^
>  File "/Users/cysimons/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
>    return self._fp.read(amt) if amt is not None else self._fp.read()
>           ^^^^^^^^^^^^^^^^^^
>  File "/Users/cysimons/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
>    data: bytes = self.__fp.read(amt)
>                  ^^^^^^^^^^^^^^^^^^^
>  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 479, in read
>    s = self.fp.read(amt)
>        ^^^^^^^^^^^^^^^^^
>  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 720, in readinto
>    return self._sock.recv_into(b)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1252, in recv_into
>    return self.read(nbytes, buffer)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1104, in read
>    return self._sslobj.read(len, buffer)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>ssl.SSLError: [SSL] record layer failure (_ssl.c:2559)
>```

Troubleshooting so far: `pip install --force-reinstall -v "osxmetadata==1.3.5"` works fine on the same machine.

**To Reproduce**
1. `brew install pipx`
2. `pipx install osxphotos`

**Expected behavior**
Installation successful

**Desktop:**
 - OS: macOS 14.6.1

**Additional context**
First install on this system.

**Comment by RhetTbull** [comment]
I have not been able to reproduce this. Will keep playing with this as I have time to see if I can figure out what's going on.

**Comment by Qhilm** [comment]
I installed the whole thing using `pip` instead of `pipx` and it works flawlessly. Don't know what this strange SSL issue is.

**Comment by rv10guy** [comment]
Same result here

**Comment by RhetTbull** [comment]
I've not been able to reproduce this. Try:

`brew update`
`brew upgrade pipx`
`pipx reinstall-all`

**Comment by abetomas** [comment]
I have a similar when upgrading a previous version of osxphotos, see below.   I was trying to upgrade osxphotos to the latest version and got an error using 'pipx reinstall-all'.  
Below is message on my terminal screen.  Also attached is the pip error log

Note:
- using Macbook M1 on Sequoia 15.0.1
- previously, I was able to run osxphotos version: 0.65.0 using venv, MacOS 14 Sonoma, python 3.12 
- recently updated to Python 3.13 (using brew)

Thank you for your help. 

*******************************
*****  terminal messages  *****
*******************************
$ pipx reinstall-all 
<<< snip other package yt-dlp reinstalled ok >>>
uninstalled osxphotos! ✨ 🌟 ✨
Fatal error from pip prevented installation. Full pip output in file:
    /Users/one/.local/pipx/logs/cmd_2024-10-26_12.10.39_pip_errors.loga

pip seemed to fail to build package:
    wrapt<1.14.0,>=1.13.3

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: metadata-generation-failed

Error installing osxphotos.
The following package(s) failed to reinstall: osxphotos
*******************************
[cmd_2024-10-26_12.10.39_pip_errors.log](https://github.com/user-attachments/files/17531423/cmd_2024-10-26_12.10.39_pip_errors.log)

**Comment by abetomas** [comment]
In addition to my earlier notes, I also tried using pip but also getting errors as below.  

$ python3 -m pip install osxphotos 
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

**Comment by RhetTbull** [comment]
OSXPhotos has not been ported to 3.13. It's on my todo list but may be a couple of weeks as I need to first update dependencies which I also maintain.

**Comment by abetomas** [comment]
> OSXPhotos has not been ported to 3.13. It's on my todo list but may be a couple of weeks as I need to first update dependencies which I also maintain.

Thanks.... it still installs ok using Python3.11 (**$ python3.11 -m pip install osxphotos**), I will use this python version instead.  Thanks for your help.

**Comment by RhetTbull** [comment]
I've updated instructions to use [uv](https://github.com/astral-sh/uv). See the [install instructions](https://github.com/RhetTbull/osxphotos?tab=readme-ov-file#installation). I'm still working on a fix for pipx but hopefully uv will work for most users for now.

**Comment by Ender-Wang** [comment]
I run into issue when installing via `pip install osxphotos` in a pipenv (then I tried `python3.11 -m pip install osxphotos` without prob):
```
❯ pip install osxphotos
Collecting osxphotos
  Using cached osxphotos-0.64.0-py3-none-any.whl.metadata (15 kB)
Collecting bitmath<1.4.0.0,>=1.3.3.1 (from osxphotos)
  Using cached bitmath-1.3.3.1.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bpylist2<5.0.0,>=4.1.1 (from osxphotos)
  Using cached bpylist2-4.1.1-py3-none-any.whl.metadata (5.5 kB)
Collecting Click<9.0,>=8.1.3 (from osxphotos)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting Mako<1.3.0,>=1.2.2 (from osxphotos)
  Using cached Mako-1.2.4-py3-none-any.whl.metadata (2.9 kB)
Collecting more-itertools<9.0.0,>=8.8.0 (from osxphotos)
  Using cached more_itertools-8.14.0-py3-none-any.whl.metadata (30 kB)
Collecting objexplore<2.0.0,>=1.6.3 (from osxphotos)
  Using cached objexplore-1.6.3-py3-none-any.whl.metadata (2.5 kB)
Collecting packaging>=21.3 (from osxphotos)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting pathvalidate<4.0.0,>=2.4.1 (from osxphotos)
  Using cached pathvalidate-3.2.1-py3-none-any.whl.metadata (12 kB)
Collecting ptpython<4.0.0,>=3.0.20 (from osxphotos)
  Using cached ptpython-3.0.29-py2.py3-none-any.whl.metadata (11 kB)
Collecting pytimeparse2<2.0.0,>=1.4.0 (from osxphotos)
  Using cached pytimeparse2-1.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting PyYAML<7.0.0,>=6.0.0 (from osxphotos)
  Using cached PyYAML-6.0.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting requests<3.0.0,>=2.27.1 (from osxphotos)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting rich-theme-manager>=0.11.0 (from osxphotos)
  Using cached rich_theme_manager-0.11.0-py3-none-any.whl.metadata (15 kB)
Collecting rich<14.0.0,>=13.5.2 (from osxphotos)
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting shortuuid<2.0.0,>=1.0.9 (from osxphotos)
  Using cached shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting strpdatetime>=0.2.0 (from osxphotos)
  Using cached strpdatetime-0.2.0-py3-none-any.whl.metadata (4.4 kB)
Collecting tenacity<9.0.0,>=8.0.1 (from osxphotos)
  Using cached tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Collecting textx<4.0.0,>=3.1.1 (from osxphotos)
  Using cached textX-3.1.1-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting toml<0.11.0,>=0.10.2 (from osxphotos)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Collecting wrapt<2.0.0,>=1.14.1 (from osxphotos)
  Using cached wrapt-1.16.0-py3-none-any.whl.metadata (6.6 kB)
Collecting wurlitzer<4.0.0,>=3.0.2 (from osxphotos)
  Using cached wurlitzer-3.1.1-py3-none-any.whl.metadata (2.5 kB)
Collecting xdg-base-dirs>=6.0.0 (from osxphotos)
  Using cached xdg_base_dirs-6.0.2-py3-none-any.whl.metadata (3.6 kB)
INFO: pip is looking at multiple versions of osxphotos to determine which version is compatible with other requirements. This could take a while.
Collecting osxphotos
  Using cached osxphotos-0.63.5-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.63.4-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.63.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.63.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.63.1-py3-none-any.whl.metadata (15 kB)
Collecting bpylist2==4.0.1 (from osxphotos)
  Using cached bpylist2-4.0.1-py3-none-any.whl.metadata (5.4 kB)
Collecting osxphotos
  Using cached osxphotos-0.63.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.62.3-py3-none-any.whl.metadata (15 kB)
INFO: pip is still looking at multiple versions of osxphotos to determine which version is compatible with other requirements. This could take a while.
  Using cached osxphotos-0.62.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.62.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.62.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.61.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.10-py3-none-any.whl.metadata (15 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached osxphotos-0.60.9-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.8-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.7-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.6-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.5-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.4-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.60.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.59.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.59.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.59.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.59.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.58.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.58.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.58.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.57.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.57.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.57.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.57.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.7-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.6-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.5-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.4-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.56.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.7-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.6-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.5-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.4-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.55.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.54.4-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.54.3-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.54.2-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.54.1-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.54.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.53.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.52.0-py3-none-any.whl.metadata (15 kB)
  Using cached osxphotos-0.51.8-py3-none-any.whl.metadata (15 kB)
Collecting osxmetadata<1.0.0,>=0.99.34 (from osxphotos)
  Using cached osxmetadata-0.99.38-py3-none-any.whl.metadata (34 kB)
Collecting pathvalidate<3.0.0,>=2.4.1 (from osxphotos)
  Using cached pathvalidate-2.5.2-py3-none-any.whl.metadata (11 kB)
Collecting photoscript<0.2.0,>=0.1.4 (from osxphotos)
  Using cached photoscript-0.1.6-py3-none-any.whl.metadata (6.0 kB)
Collecting pyobjc-core<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc-core-8.5.1.tar.gz (789 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyobjc-framework-AVFoundation<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_AVFoundation-8.5.1-cp36-abi3-macosx_11_0_universal2.whl.metadata (2.4 kB)
Collecting pyobjc-framework-AppleScriptKit<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_AppleScriptKit-8.5.1-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting pyobjc-framework-AppleScriptObjC<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_AppleScriptObjC-8.5.1-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting pyobjc-framework-Cocoa<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc-framework-Cocoa-8.5.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyobjc-framework-CoreServices<9.0,>=7.2 (from osxphotos)
  Using cached pyobjc_framework_CoreServices-8.5.1-cp36-abi3-macosx_11_0_universal2.whl.metadata (2.4 kB)
Collecting pyobjc-framework-Metal<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_Metal-8.5.1-cp36-abi3-macosx_11_0_universal2.whl.metadata (2.2 kB)
Collecting pyobjc-framework-Photos<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_Photos-8.5.1-cp36-abi3-macosx_11_0_universal2.whl.metadata (2.2 kB)
Collecting pyobjc-framework-Quartz<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc-framework-Quartz-8.5.1.tar.gz (3.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyobjc-framework-Vision<9.0,>=7.3 (from osxphotos)
  Using cached pyobjc_framework_Vision-8.5.1-cp36-abi3-macosx_11_0_universal2.whl.metadata (2.3 kB)
Collecting pytimeparse2==1.4.0 (from osxphotos)
  Using cached pytimeparse2-1.4.0-py3-none-any.whl.metadata (4.0 kB)
Collecting rich<13.0.0,>=11.2.0 (from osxphotos)
  Using cached rich-12.6.0-py3-none-any.whl.metadata (18 kB)
Collecting shortuuid==1.0.9 (from osxphotos)
  Using cached shortuuid-1.0.9-py3-none-any.whl.metadata (5.7 kB)
Collecting textx<3.0.0,>=2.3.0 (from osxphotos)
  Using cached textX-2.3.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting wrapt<1.14.0,>=1.13.3 (from osxphotos)
  Using cached wrapt-1.13.3.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 69, in __getattr__
          return next(
              ast.literal_eval(value)
              for target, value in self._find_assignments()
              if isinstance(target, ast.Name) and target.id == attr
          )
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 70, in <genexpr>
          ast.literal_eval(value)
          ~~~~~~~~~~~~~~~~^^^^^^^
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 114, in literal_eval
          return _convert(node_or_string)
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 113, in _convert
          return _convert_signed_num(node)
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 87, in _convert_signed_num
          return _convert_num(node)
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 78, in _convert_num
          _raise_malformed_node(node)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ast.py", line 75, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x1027a8d10>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 183, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 75, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/enderwang/.local/share/virtualenvs/osxphotos-VxX2vT-7/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/enderwang/.local/share/virtualenvs/osxphotos-VxX2vT-7/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/enderwang/.local/share/virtualenvs/osxphotos-VxX2vT-7/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 376, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 41, in <module>
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 157, in setup
          dist.parse_config_files()
          ~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/Users/enderwang/.local/share/virtualenvs/osxphotos-VxX2vT-7/lib/python3.13/site-packages/_virtualenv.py", line 22, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 651, in parse_config_files
          setupcfg.parse_configuration(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
              self, self.command_options, ignore_option_errors=ignore_option_errors
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 199, in parse_configuration
          meta.parse()
          ~~~~~~~~~~^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 512, in parse
          section_parser_method(section_options)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 487, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 305, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 604, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 429, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 186, in read_attr
          module = _load_spec(spec, module_name)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-build-env-o4v64jje/overlay/lib/python3.13/site-packages/setuptools/config/expand.py", line 207, in _load_spec
          spec.loader.exec_module(module)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-install-rrmze54m/wrapt_b64913af10464ac0af1a844c3a6a1816/src/wrapt/__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
                  synchronized)
        File "/private/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/pip-install-rrmze54m/wrapt_b64913af10464ac0af1a844c3a6a1816/src/wrapt/decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py). Did you mean: 'formatargvalues'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by RhetTbull** [comment]
@Ender-Wang I'm confused by what you're seeing. I think the version of osxphotos you may be running is different than what you tried to install. In the `pip install osxphotos` errors above, I see:

```
      ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/inspect.py). Did you mean: 'formatargvalues'?
      [end of output]
```

Which is a python 3.13 error and osxphotos does not yet work with python 3.13 (working on that).

The second run-time error is from python 3.11

```
/opt/homebrew/lib/python3.11/site-packages/osxphotos/photosdb/photosdb.py:691 in _copy_db_file   │
```

The error appears to be because osxphotos doesn't have permission access your Photos library database:

```
OSError: Error copying /Users/enderwang/Pictures/Photos Library.photoslibrary/database/photos.db to 
/var/folders/63/nfnqb0r15rsd8pygw54t1qjw0000gq/T/osxphotos_t48yq8hq/photos.db: [Errno 1] Operation not permitted: 
'/Users/enderwang/Pictures/Photos Library.photoslibrary/database/photos.db'
```

The error handling could be better -- it should print a helpful error message instead of a stack trace (`osxphotos export` does this but the other commands such as `osxphotos albums` do not). I'll open a separate issue for that.

Check in `System Settings > Privacy & Security > Photos` to ensure your terminal has been granted full access and also in `System Settings > Privacy & Security > Full Disk Access` to ensure the same.

**Comment by Ender-Wang** [comment]
Thanks, now it works after granding Terminal full disk access.
